export const questions = [
  {
    id: 1,
    question: "What is the primary benefit of using ECOpact?",
    options: [
      "Increased aesthetic value",
      "Reduced carbon footprint",
      "Higher load-bearing capacity",
      "Waterproofing properties",
      "Resistance to extreme weather",
    ],
    correctAnswer: "2",
  },
  {
    id: 2,
    question: "In which scenario would DynaMax be most suitable?",
    options: [
      "Restoring a historic facade",
      "Constructing a pedestrian walkway",
      "Building a long-span bridge",
      "Waterproofing a roof",
      "Promoting coral growth",
    ],
    correctAnswer: "3",
  },
  {
    id: 3,
    question: "What distinguishes Ductal from conventional concrete?",
    options: [
      "High carbon footprint",
      "Limited strength",
      "Superior flexibility and durability",
      "Inability to resist weathering",
      "Exclusive use in roofing",
    ],
    correctAnswer: "3",
  },
  {
    id: 4,
    question: "What is the main purpose of EcoFuel?",
    options: [
      "Decorative finishes",
      "Alternative to fossil fuels",
      "Enhanced bonding in construction",
      "Marine ecosystem support",
      "Stormwater management",
    ],
    correctAnswer: "2",
  },
  {
    id: 5,
    question: "Which application is best suited for Tector?",
    options: [
      "Long-span bridge construction",
      "Decorative finishes and bonding",
      "Marine ecosystem enhancement",
      "Permeable concrete for water management",
      "High-strength roofing",
    ],
    correctAnswer: "2",
  },
  {
    id: 6,
    question: "Which feature is a key characteristic of Elevate?",
    options: [
      "Coral growth promotion",
      "High permeability for stormwater management",
      "Energy-efficient and durable roofing",
      "High-strength mortar for bonding",
      "Reduced carbon emissions",
    ],
    correctAnswer: "3",
  },
  {
    id: 7,
    question: "What sets Malarkey shingles apart from traditional roofing?",
    options: [
      "Support for coral growth",
      "Use of recycled materials and weather resistance",
      "Suitability for pedestrian walkways",
      "Permeable structure for stormwater control",
      "Ultra-high strength",
    ],
    correctAnswer: "2",
  },
  {
    id: 8,
    question: "What is the primary benefit of Smart Blend?",
    options: [
      "Aesthetic finishes",
      "Cost-effective concrete formulations",
      "High weather resistance for roofs",
      "Coral growth support",
      "Enhanced flexibility in concrete",
    ],
    correctAnswer: "2",
  },
  {
    id: 9,
    question: "Which feature makes HydroMedia unique?",
    options: [
      "High carbon footprint",
      "Resistance to extreme weather",
      "Permeability for stormwater management",
      "Advanced roofing aesthetics",
      "High tensile strength",
    ],
    correctAnswer: "3",
  },
  {
    id: 10,
    question: "What is the primary benefit of Bioactive Concrete?",
    options: [
      "Supporting marine life and coral growth",
      "Durability in roofing",
      "Permeability for urban drainage",
      "Decorative finishes for facades",
      "Energy efficiency in homes",
    ],
    correctAnswer: "1",
  },
  {
    id: 11,
    question: "Which feature makes Tector Print stand out?",
    options: [
      "Self-healing for marine ecosystems",
      "Compatibility with 3D printing for complex designs",
      "High strength for skyscrapers",
      "Decorative finishes for traditional buildings",
      "Energy-efficient roofing",
    ],
    correctAnswer: "2",
  },
];
